---
# Source: datahub-prerequisites/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datahub-prerequisites-mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.5.4
    app.kubernetes.io/instance: datahub-prerequisites
    app.kubernetes.io/managed-by: Helm
  annotations:
secrets:
  - name: mysql-secrets
