---
# Source: datahub-prerequisites/charts/mysql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: datahub-prerequisites-mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.5.4
    app.kubernetes.io/instance: datahub-prerequisites
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: datahub-prerequisites
    app.kubernetes.io/component: primary
