---
# Source: datahub/charts/datahub-gms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: datahub-datahub-gms
  labels:
    helm.sh/chart: datahub-gms-0.2.3
    app.kubernetes.io/name: datahub-gms
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: datahub-gms
    app.kubernetes.io/instance: datahub
