---
# Source: datahub/charts/datahub-gms/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datahub-datahub-gms
  labels:
    helm.sh/chart: datahub-gms-0.2.3
    app.kubernetes.io/name: datahub-gms
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
