{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-auth-secrets" -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-auth-secrets"
type: Opaque
data:
  system_client_secret: {{ randAlphaNum 20 | b64enc | quote }}
  token_service_signing_key: {{ randAlphaNum 20 | b64enc | quote }}
{{- end -}}