{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-auth-secrets" -}}
{{- if (and (not $secret) (.Values.global.datahub.metadata_service_authentication.provisionSecrets)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-auth-secrets"
type: Opaque
data:
  system_client_secret: {{ randAlphaNum 32 | b64enc | quote }}
  token_service_signing_key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}