{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-auth-secrets" -}}
{{- if .Values.global.datahub.metadata_service_authentication.provisionSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-auth-secrets"
type: Opaque
data:
  # check, if a secret is already set
  {{- if or (not $secret) (not $secret.data) }}
  # if not set, then generate a new secret
  system_client_secret: {{ randAlphaNum 32 | b64enc | quote }}
  token_service_signing_key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  # if set, then use the old value
  system_client_secret: {{ index $secret.data "system_client_secret" }}
  token_service_signing_key: {{ index $secret.data "token_service_signing_key" }}
  {{ end }}
{{- end -}}