{{- if .Values.global.helmHooks }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-reader
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
{{- end }}
---
{{- if .Values.global.helmHooks }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-reader
subjects:
- kind: ServiceAccount
  name: datahub-gms
  namespace: {{ .Release.Namespace }}
{{- end }}