{{- $asa := .Values.global.datahub.appServiceAccount | default dict }}
{{- if $asa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "global.datahub.appServiceAccount.name is required when create is true" $asa.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datahub.labels" . | nindent 4 }}
  {{- with $asa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
