apiVersion: v1
entries:
  cp-helm-charts:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-11-12T12:50:42.857908+02:00"
    dependencies:
    - condition: cp-kafka.enabled
      name: cp-kafka
      repository: file://./charts/cp-kafka
      version: 0.1.0
    - condition: cp-zookeeper.enabled
      name: cp-zookeeper
      repository: file://./charts/cp-zookeeper
      version: 0.1.0
    - condition: cp-schema-registry.enabled
      name: cp-schema-registry
      repository: file://./charts/cp-schema-registry
      version: 0.1.0
    - condition: cp-kafka-rest.enabled
      name: cp-kafka-rest
      repository: file://./charts/cp-kafka-rest
      version: 0.1.0
    - condition: cp-kafka-connect.enabled
      name: cp-kafka-connect
      repository: file://./charts/cp-kafka-connect
      version: 0.1.0
    - condition: cp-ksql-server.enabled
      name: cp-ksql-server
      repository: file://./charts/cp-ksql-server
      version: 0.1.0
    - condition: cp-control-center.enabled
      name: cp-control-center
      repository: file://./charts/cp-control-center
      version: 0.1.0
    description: A Helm chart for Confluent Platform Community Edition
    digest: 6adf7734ed23975318a57842e8cc612217a89bc427b9787c1725e0cb4a886c45
    name: cp-helm-charts
    urls:
    - charts/cp-helm-charts-0.6.0.tgz
    version: 0.6.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 7.9.3
    created: "2021-11-12T12:50:42.861204+02:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: 853609052207a9e5f6e67b5f51525262376b4f6bdfb996ae2723ef94ecda536b
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - charts/elasticsearch-7.9.3.tgz
    version: 7.9.3
  kafka:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 2.8.0
    created: "2021-11-12T12:50:42.867615+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: zookeeper.enabled
      name: zookeeper
      repository: https://charts.bitnami.com/bitnami
      version: 6.x.x
    description: Apache Kafka is a distributed streaming platform.
    digest: 0e178b18f7380272ee6617e9af36b4e31b7a494c8f81430c222a8f12dfd01d24
    home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
    icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
    keywords:
    - kafka
    - zookeeper
    - streaming
    - producer
    - consumer
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: kafka
    sources:
    - https://github.com/bitnami/bitnami-docker-kafka
    - https://kafka.apache.org/
    urls:
    - charts/kafka-12.17.4.tgz
    version: 12.17.4
  mysql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 8.0.24
    created: "2021-11-12T12:50:42.872123+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Chart to create a Highly available MySQL cluster
    digest: d3d67cd23ee23e5e620c99d32e5c6bc8bdb2d993a5b0976f6fb56df51277b5b3
    home: https://github.com/bitnami/charts/tree/master/bitnami/mysql
    icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
    keywords:
    - mysql
    - database
    - sql
    - cluster
    - high availability
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mysql
    sources:
    - https://github.com/bitnami/bitnami-docker-mysql
    - https://mysql.com
    urls:
    - charts/mysql-8.5.4.tgz
    version: 8.5.4
  neo4j:
  - apiVersion: v1
    appVersion: 4.2.2
    created: "2021-11-12T12:50:42.874431+02:00"
    description: Neo4j is the world's leading graph database
    digest: 4484d915b96f09f6d558796060f2e271479f4d98e2fb21bb80477f208cfe1226
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    keywords:
    - graph
    - database
    - cypher
    maintainers:
    - email: david.allen@neo4j.com
      name: moxious
    - email: bledi.feshti@neo4j.com
      name: bfeshti
    - email: mark.needham@neo4j.com
      name: mneedham
    name: neo4j
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/neo4j-contrib/neo4j-helm
    urls:
    - charts/neo4j-4.2.2-1.tgz
    version: 4.2.2-1
  neo4j-community:
  - apiVersion: v2
    appVersion: 4.2.4
    created: "2021-11-12T12:50:42.875571+02:00"
    description: Neo4j is the world's leading graph database
    digest: a4b7189ebd2569bf3725821961248c27af89735e5a6b8ac2adf79df323dac6b2
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/neo4j-contrib/neo4j-helm
    - https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community
    urls:
    - charts/neo4j-community-1.2.5.tgz
    version: 1.2.5
generated: "2021-11-12T12:50:42.852663+02:00"
