apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "datahub-mae-consumer" }}
  labels:
    {{- include "datahub-mae-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
    {{- if .Values.global.datahub.monitoring.enablePrometheus }}
    {{- $mode := include "datahub-mae-consumer.monitoring.metricsMode" . }}
    {{- if or (eq $mode "legacy") (eq $mode "jmx_and_actuator") }}
    - name: {{ .Values.global.datahub.monitoring.portName }}
      port: {{ include "datahub-mae-consumer.monitoring.jmxPort" . }}
      targetPort: {{ .Values.global.datahub.monitoring.portName }}
      protocol: TCP
    {{- end }}
    {{- if or (eq $mode "jmx_and_actuator") (eq $mode "actuator_only") }}
    - name: prometheus
      port: {{ include "datahub-mae-consumer.monitoring.actuatorPrometheusPort" . }}
      targetPort: prometheus
      protocol: TCP
    {{- end }}
    {{- end }}
  selector:
    {{- include "datahub-mae-consumer.selectorLabels" . | nindent 4 }}
