{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-encryption-secrets" -}}
{{- $data := $secret.data | default dict -}}
{{- with .Values.global.datahub.encryptionKey.provisionSecret }}

{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-encryption-secrets"
type: Opaque
data: 
  {{- if .autoGenerate }}
  encryption_key_secret: {{ get $data "encryption_key_secret" | default (randAlphaNum 20 | b64enc | quote) }}
  {{- else }}
  encryption_key_secret: {{ .secretValues.encryptionKey | b64enc | quote }}
  {{- end }}

{{- end }}
{{- end -}}
