{{- if index .Values.neo4jCommunity.ingress.enabled -}}
{{- $fullName := include "neo4jCommunity.fullname" . -}}
{{- $svcPort := .Values.neo4jCommunity.service.port -}}
{{- $ingressApiVersion := include "neo4jCommunity.ingress.apiVersion" . -}}
apiVersion: {{ template "neo4jCommunity.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "neo4jCommunity.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.neo4jCommunity.ingress.className }}
  ingressClassName: {{ .Values.neo4jCommunity.ingress.className | quote }}
{{- end }}
{{- if .Values.neo4jCommunity.ingress.tls }}
  tls:
  {{- range .Values.neo4jCommunity.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.neo4jCommunity.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .redirectPaths }}
          - path: {{ .path }}
            {{- if eq $ingressApiVersion "networking.k8s.io/v1" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
            {{- else }}
            backend:
              serviceName: {{ .name }}
              servicePort: {{ .port }}
            {{- end }}
        {{- end }}
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq $ingressApiVersion "networking.k8s.io/v1" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
