---
# Source: datahub/templates/datahub-auth-secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-auth-secrets"
type: Opaque
data:
  system_client_secret: "c1ZrMW5RVWhyQkRMbE5JZmVyazB6elVJbTBkNVpXWjg="
  token_service_signing_key: "VGFldklUQkNkZnNZR1NJMWJWWDc4SVo4TGdBQWZHakY="
