---
# Source: datahub/templates/elasticsearch-setup-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-elasticsearch-setup-job
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "datahub"
    app.kubernetes.io/version: 0.8.27
    helm.sh/chart: "datahub-0.2.53"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      volumes:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      containers:
        - name: elasticsearch-setup-job
          image: "linkedin/datahub-elasticsearch-setup:v0.8.27"
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-master"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: DATAHUB_ANALYTICS_ENABLED
              value: "true"
          securityContext:
            runAsUser: 1000
          volumeMounts:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
