name: Release Charts

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  release:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Generate new version
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: true # just generates the new tag, but doesn't push it
      - name: Bump chart versions
        uses: mikefarah/yq@master
        with:
          cmd: ./.github/scripts/bump-chart-versions.sh ${{ steps.tag.outputs.new_tag }}
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add Helm repos
        run: |
          helm repo add elasticsearch https://helm.elastic.co
          helm repo add neo4j https://neo4j-contrib.github.io/neo4j-helm
          helm repo add neo4j-community https://equinor.github.io/helm-charts/charts
          helm repo add mysql https://charts.bitnami.com/bitnami
          helm repo add cp-helm-charts https://confluentinc.github.io/cp-helm-charts
          helm repo add kafka https://charts.bitnami.com/bitnami
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_repo_url: https://helm.datahubproject.io
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Commit push'
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: '[skip ci] Update chart versions'
          branch: 'master'
          file_pattern: "*.yaml" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag the the update-charts commit 
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: false
          DEFAULT_BUMP: patch
